# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.iuclid_search_section import IuclidSearchSection

class TestIuclidSearchSection(unittest.TestCase):
    """IuclidSearchSection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIuclidSearchSection(self):
        """Test IuclidSearchSection"""
        # inst = IuclidSearchSection()

if __name__ == '__main__':
    unittest.main()
