# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.about_text_pair import AboutTextPair

class TestAboutTextPair(unittest.TestCase):
    """AboutTextPair unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AboutTextPair:
        """Test AboutTextPair
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AboutTextPair`
        """
        model = AboutTextPair()
        if include_optional:
            return AboutTextPair(
                label = '',
                value = ''
            )
        else:
            return AboutTextPair(
        )
        """

    def testAboutTextPair(self):
        """Test AboutTextPair"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
