# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchApi()

    def tearDown(self) -> None:
        pass

    def test_api_v6_search_cas_cas_ignore_stereo_get(self) -> None:
        """Test case for api_v6_search_cas_cas_ignore_stereo_get

        Performs a search by CAS number
        """
        pass

    def test_api_v6_search_chemical_chem_id_get(self) -> None:
        """Test case for api_v6_search_chemical_chem_id_get

        Returns a chemical structure from the provided chemId containing CAS# and Smiles
        """
        pass

    def test_api_v6_search_databases_get(self) -> None:
        """Test case for api_v6_search_databases_get

        Lists all databases and inventories
        """
        pass

    def test_api_v6_search_ecnumber_ecnumber_ignore_stereo_get(self) -> None:
        """Test case for api_v6_search_ecnumber_ecnumber_ignore_stereo_get

        Performs a search by EC number
        """
        pass

    def test_api_v6_search_name_name_options_ignore_stereo_get(self) -> None:
        """Test case for api_v6_search_name_name_options_ignore_stereo_get

        Performs a search by name
        """
        pass

    def test_api_v6_search_smiles_register_unknown_ignore_stereo_get(self) -> None:
        """Test case for api_v6_search_smiles_register_unknown_ignore_stereo_get

        Performs a search by SMILES and returns a SmilesSearchResult object as a result
        """
        pass


if __name__ == '__main__':
    unittest.main()
