# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.export_api import ExportApi


class TestExportApi(unittest.TestCase):
    """ExportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExportApi()

    def tearDown(self) -> None:
        pass

    def test_api_v6_export_list_smi_get(self) -> None:
        """Test case for api_v6_export_list_smi_get

        Exports the given chemicals as a .smi text file
        """
        pass


if __name__ == '__main__':
    unittest.main()
