# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.iuclidid_raw_toolbox_id import IUCLIDIdRawToolboxId

class TestIUCLIDIdRawToolboxId(unittest.TestCase):
    """IUCLIDIdRawToolboxId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IUCLIDIdRawToolboxId:
        """Test IUCLIDIdRawToolboxId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IUCLIDIdRawToolboxId`
        """
        model = IUCLIDIdRawToolboxId()
        if include_optional:
            return IUCLIDIdRawToolboxId(
                json_search_details = '',
                raw_toolbox_id = 56,
                iuclid_name = '',
                source_id = 56,
                iuclid_entity_id = '',
                type = 'Dossier'
            )
        else:
            return IUCLIDIdRawToolboxId(
        )
        """

    def testIUCLIDIdRawToolboxId(self):
        """Test IUCLIDIdRawToolboxId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
