# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.simulator import Simulator

class TestSimulator(unittest.TestCase):
    """Simulator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Simulator:
        """Test Simulator
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Simulator`
        """
        model = Simulator()
        if include_optional:
            return Simulator(
                caption = '',
                guid = '',
                is_observed = True,
                product_name = ''
            )
        else:
            return Simulator(
        )
        """

    def testSimulator(self):
        """Test Simulator"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
