# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.qsar_api import QsarApi


class TestQsarApi(unittest.TestCase):
    """QsarApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QsarApi()

    def tearDown(self) -> None:
        pass

    def test_api_v6_qsar_apply_qsar_guid_chem_id_get(self) -> None:
        """Test case for api_v6_qsar_apply_qsar_guid_chem_id_get

        Applies the specified QSAR model onto the provided chemical
        """
        pass

    def test_api_v6_qsar_domain_qsar_guid_chem_id_get(self) -> None:
        """Test case for api_v6_qsar_domain_qsar_guid_chem_id_get

        Checks whether the chemicals falls within the domain of the specified QSAR model
        """
        pass

    def test_api_v6_qsar_list_position_get(self) -> None:
        """Test case for api_v6_qsar_list_position_get

        Retrieves all QSAR models that are associated to the provided position of the endpoint tree
        """
        pass


if __name__ == '__main__':
    unittest.main()
