# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.structure_api import StructureApi


class TestStructureApi(unittest.TestCase):
    """StructureApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StructureApi()

    def tearDown(self) -> None:
        pass

    def test_api_v6_structure_canonize_get(self) -> None:
        """Test case for api_v6_structure_canonize_get

        Returns the canonized version of the provided smiles
        """
        pass

    def test_api_v6_structure_connectivity_get(self) -> None:
        """Test case for api_v6_structure_connectivity_get

        Returns connectivity string for the supplied smiles
        """
        pass


if __name__ == '__main__':
    unittest.main()
