# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.grouping_api import GroupingApi


class TestGroupingApi(unittest.TestCase):
    """GroupingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupingApi()

    def tearDown(self) -> None:
        pass

    def test_api_v6_grouping_chem_id_profiler_guid_get(self) -> None:
        """Test case for api_v6_grouping_chem_id_profiler_guid_get

        Creates a group of chemicals from the given databases having same profiles as the target chemical by the specified profiler
        """
        pass


if __name__ == '__main__':
    unittest.main()
