# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.iuclidid_type import IUCLIDIdType

class TestIUCLIDIdType(unittest.TestCase):
    """IUCLIDIdType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIUCLIDIdType(self):
        """Test IUCLIDIdType"""
        # inst = IUCLIDIdType()

if __name__ == '__main__':
    unittest.main()
