# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.profiling_api import ProfilingApi


class TestProfilingApi(unittest.TestCase):
    """ProfilingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProfilingApi()

    def tearDown(self) -> None:
        pass

    def test_api_v6_profiling_all_chem_id_get(self) -> None:
        """Test case for api_v6_profiling_all_chem_id_get

        Profiles the provided chemical with all available profilers
        """
        pass

    def test_api_v6_profiling_get(self) -> None:
        """Test case for api_v6_profiling_get

        Requests all available profilers
        """
        pass

    def test_api_v6_profiling_profiler_guid_chem_id_simulator_guid_get(self) -> None:
        """Test case for api_v6_profiling_profiler_guid_chem_id_simulator_guid_get

        Profiles the provided chemical with the specified profiler
        """
        pass

    def test_api_v6_profiling_profiler_guid_get(self) -> None:
        """Test case for api_v6_profiling_profiler_guid_get

        Returns all of the available categories for a provided profiler
        """
        pass

    def test_api_v6_profiling_profiler_guid_info_get(self) -> None:
        """Test case for api_v6_profiling_profiler_guid_info_get

        Provides general information for the specified profiler
        """
        pass

    def test_api_v6_profiling_profiler_guid_literature_get(self) -> None:
        """Test case for api_v6_profiling_profiler_guid_literature_get

        Provides literature for the given category in the specified profiler
        """
        pass

    def test_api_v6_profiling_relevancies_get(self) -> None:
        """Test case for api_v6_profiling_relevancies_get

        Requests profiles that are relevant to the specified endpoint position and metadata
        """
        pass


if __name__ == '__main__':
    unittest.main()
