# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.iuclid_api import IuclidApi


class TestIuclidApi(unittest.TestCase):
    """IuclidApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IuclidApi()

    def tearDown(self) -> None:
        pass

    def test_api_v6_iuclid_cas_cas_get(self) -> None:
        """Test case for api_v6_iuclid_cas_cas_get

        Find IUCLID entities by CAS Number
        """
        pass

    def test_api_v6_iuclid_databases_get(self) -> None:
        """Test case for api_v6_iuclid_databases_get

        Retrieve a list of databases with IUCLID imports
        """
        pass

    def test_api_v6_iuclid_ecnumber_ecnumber_get(self) -> None:
        """Test case for api_v6_iuclid_ecnumber_ecnumber_get

        Find IUCLID entities by EC Number
        """
        pass

    def test_api_v6_iuclid_name_get(self) -> None:
        """Test case for api_v6_iuclid_name_get

        Find IUCLID entities by Chemical name
        """
        pass

    def test_api_v6_iuclid_smiles_is_subfragment_search_get(self) -> None:
        """Test case for api_v6_iuclid_smiles_is_subfragment_search_get

        Find IUCLID entities by SMILES (exact or substructure)
        """
        pass


if __name__ == '__main__':
    unittest.main()
