# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.workflows_api import WorkflowsApi


class TestWorkflowsApi(unittest.TestCase):
    """WorkflowsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkflowsApi()

    def tearDown(self) -> None:
        pass

    def test_api_v6_workflows_get(self) -> None:
        """Test case for api_v6_workflows_get

        Requests all available workflows
        """
        pass

    def test_api_v6_workflows_workflow_guid_chem_id_get(self) -> None:
        """Test case for api_v6_workflows_workflow_guid_chem_id_get

        Executes a workflow with a given chemical
        """
        pass


if __name__ == '__main__':
    unittest.main()
