# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.substance_type import SubstanceType

class TestSubstanceType(unittest.TestCase):
    """SubstanceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubstanceType(self):
        """Test SubstanceType"""
        # inst = SubstanceType()

if __name__ == '__main__':
    unittest.main()
