# coding: utf-8

"""
    Toolbox WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Qsar(BaseModel):
    """
    Qsar
    """ # noqa: E501
    caption: Optional[StrictStr] = Field(default=None, description="Caption of the Toolbox Object", alias="Caption")
    guid: Optional[StrictStr] = Field(default=None, description="Unique identifier of the Toolbox Object", alias="Guid")
    position: Optional[StrictStr] = Field(default=None, alias="Position")
    donator: Optional[StrictStr] = Field(default=None, alias="Donator")
    __properties: ClassVar[List[str]] = ["Caption", "Guid", "Position", "Donator"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Qsar from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if caption (nullable) is None
        # and model_fields_set contains the field
        if self.caption is None and "caption" in self.model_fields_set:
            _dict['Caption'] = None

        # set to None if position (nullable) is None
        # and model_fields_set contains the field
        if self.position is None and "position" in self.model_fields_set:
            _dict['Position'] = None

        # set to None if donator (nullable) is None
        # and model_fields_set contains the field
        if self.donator is None and "donator" in self.model_fields_set:
            _dict['Donator'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Qsar from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Caption": obj.get("Caption"),
            "Guid": obj.get("Guid"),
            "Position": obj.get("Position"),
            "Donator": obj.get("Donator")
        })
        return _obj


